### ISSUE TITLE
Sponsors display

### ISSUE THREAD

**Issue by shaib** [Hamakor/pycon-israel#18]
We need to design and implement the display of sponsors -- certainly on the home page, maybe also on the sidebar? do some weighted lottery and present one of the sponsors each time there?

**Comment by AmitAronovitch** [comment]
Current state (in the sponsors branch + some messages that need to be integrated from slack):

The sidebar (appears in pinax pages, not in homepage) has a design: column of smaller icons, divided  by sponsorship levels (I'm guessing the internal ordering in each level is by object id. If required we can add priorities)

For the main page, I copied the base design from PyCon - it is just a grid of icons - I think no ordering at all. Eldan suggested we order by sponsorship levels and follow last year's design (he posted some snippets on #site, and also some style-fix related to my branch).

**Comment by shaib** [comment]
Home page and sidebar exist, @AmitAronovitch talked about a dedicated sponsors page that is in fact included in symposion.
