### ISSUE TITLE
Homepage: Design contents

### ISSUE THREAD

**Issue by shaib** [Hamakor/pycon-israel#2]
We need to decide what goes on the homepage and how. Our own past confs are not exactly available for review (changed to post-conf home pages) but we can take note from e.g. PyCon US

**Comment by moshe742** [comment]
on the home page we should have:
* the sponsors (either with their levels or without) and call for sponsors if we are still looking.
* CFP link with a bit of description
* registration when relevant
* main event (a few words of description should be enough, the idea is to get people to go and see the actual data when it's published)
* workshops and django girls, same as the main event
* contact us section
I think the idea should be something to make the visitor want to get more data and go to the relevant links they want, not give a lot of data (except for the sponsors may be)

**Comment by AmitAronovitch** [comment]
re: sponsors: note that there's a sponsors sidebar that appears in all other pages (except the home). I'm guessing (suggesting?) that this is because sponsors should appear at the bottom in the homepage, or at other suitable place to maximize design attractiveness

**Comment by moshe742** [comment]
I agree, on the homepage it shouldn't be at the top, the order above is not necessarily the order it should be.
A logical order would be (I think):
* CFP (when relevant)
* registration (when relevant)
* main event
* workshops/django girls
* sponsors
* contact us
if you have a better idea you are welcome to suggest it :-)

**Comment by shaib** [comment]
Design is, essentially, done. Thanks.
