### ISSUE TITLE
Translations broken on Heroku

### ISSUE THREAD

**Issue by AmitAronovitch** [Hamakor/pycon-israel#30]
On Heroku deployment: If you go to COC or to Venue pages, you see that the title of the sidebar is "Sponsors" even when we change language to Hebrew.
This is because "gettext" is not included in the Heroku Python buildpack (so the dyno does not have the lib, and ./manage compilemessages fails with an error).

Possible solution is to git-add the translation. Other might be to add the missing package. e.g. this https://github.com/grauwoelfchen/heroku-buildpack-gettext

**Comment by shaib** [comment]
(Actually #29 makes the side-bar title non-translated English. to match the post texts which appear to be always English. The translations problem in general still stands, of course)

**Comment by shaib** [comment]
Unbroken since #34 .
