### ISSUE TITLE
Keynotes (nonexistent) room referenced in speaker  page

### ISSUE THREAD

**Issue by shaib** [Hamakor/pycon-israel#61]
It is visible e.g. on https://il.pycon.org/2018/en/speakers/profile/134/

**Comment by shaib** [comment]
![screenshot_20180518_190906](https://user-images.githubusercontent.com/129187/40245923-a7450392-5acf-11e8-8e2a-c6668c611463.png)

**Comment by AmitAronovitch** [comment]
merged & deployed
